export default {
  SET_SELECTED_ACTION: 'userActions/SET_SELECTED_ACTION',
  UPDATE_ACTIONS_HISTORY: 'userActions/UPDATE_ACTIONS_HISTORY',
  WIPE_ACTIONS_HISTORY: 'userAction/WIPE_ACTIONS_HISTORY',
};
